### ISSUE TITLE
Follow Docs for Kubevirt + CDI and Document any gotchas

### ISSUE THREAD

**Issue by hh** [ii/infra#7]
Ideally we should be able to use KubeVirt as part of CAPI to deploy Talos

- https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt

**Comment by BobyMCbobs** [comment]
got KubeVirt Operator installed and KubeVirt should come up after that.
VM creation process will be with a VirtualMachine resource, like

https://kubevirt.io/labs/manifests/vm.yaml

this can be performed in Terraform or in the Flux portions of the repo

**Comment by hh** [comment]
@heyste can you add information on one of the kids day QEMU or similar images so @BobyMCbobs can make them boot tomorrow?

**Comment by hh** [comment]
- [x] Install the CDI : https://kubevirt.io/labs/kubernetes/lab2

**Comment by hh** [comment]
Debugging here:
```
kubectl describe dv fedora  | grep Events: -A5
Events:
  Type     Reason            Age                 From                          Message
  ----     ------            ----                ----                          -------
  Normal   ErrClaimNotValid  93s                 datavolume-import-controller  no accessMode defined DV nor on StorageProfile for longhorn StorageClass
  Warning  ErrClaimNotValid  37s (x17 over 93s)  datavolume-import-controller  DataVolume.storage spec is missing accessMode and volumeMode, cannot get access mode from StorageProfile longhorn
```

**Comment by hh** [comment]
Hitting this issue: https://github.com/kubevirt/kubevirt/issues/7078#issuecomment-1022970147

```
$ kubectl explain dv.spec.storage.volumeMode
GROUP:      cdi.kubevirt.io
KIND:       DataVolume
VERSION:    v1beta1

FIELD: volumeMode <string>

DESCRIPTION:
    volumeMode defines what type of volume is required by the claim. Value of
    Filesystem is implied when not included in claim spec.
```

    
```
$ kubectl explain dv.spec.storage.accessModes
GROUP:      cdi.kubevirt.io
KIND:       DataVolume
VERSION:    v1beta1

FIELD: accessModes <[]string>

DESCRIPTION:
    AccessModes contains the desired access modes the volume should have. More
    info:
    https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
 ```

**Comment by hh** [comment]
https://kubevirt.io/user-guide/operations/containerized_data_importer/#supported-image-formats

> CDI supports the raw and qcow2 image formats which are supported by qemu. See the [qemu documentation](https://www.qemu.org/docs/master/system/images.html#disk-image-file-formats) for more details. Bootable ISO images can also be used and are treated like raw images. Images may be compressed with either the gz or xz format.

**Comment by hh** [comment]
Looks like `spec.accessModes` is required, going with `ReadWriteOnce`

```yaml
metadata:
  name: "fedora"
spec:
  storage:
    volumeMode: block # or filesystem
    accessModes:
      - ReadWriteOnce # Necessary as it's no longer has a default
    resources:
      requests:
        storage: 5Gi
  source:
    http:
      url: "https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz"
```

**Comment by hh** [comment]
Still having trouble connecting via ssh:
```
ii@cloudnative-paris:~$ kubectl get vmi
NAME     AGE     PHASE     IP            NODENAME                          READY
testvm   42m     Running   10.244.1.30   cloudnative-coop-bursting-krill   True
vm1      2m53s   Running   10.244.0.33   cloudnative-coop-quick-eft        True
ii@cloudnative-paris:~$ ssh -v fedora@10.244.0.33
OpenSSH_9.3p1 Ubuntu-1ubuntu3.2, OpenSSL 3.0.10 1 Aug 2023
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 10.244.0.33 [10.244.0.33] port 22.
debug1: connect to address 10.244.0.33 port 22: No route to host
ssh: connect to host 10.244.0.33 port 22: No route to host
```

**Comment by hh** [comment]
Let's chat with @usrbinkat at KubCon, she's dig this I think.

**Comment by usrbinkat** [comment]
@hh did someone say kubevirt? :)

**Comment by hh** [comment]
@usrbinkat hello lovely human!

I'm working on a system that will use kubevirt to help contributors develop and demo CNCF projects. I'm just now looping back to this after migrating the sharing.io cluster over to Hong Kong.

I'd like to integrate these with cloud / web based collaborative environments.

I think I am just running into learning curve issues with KubeVirt, getting a bit stuck in *lab2*:

https://kubevirt.io/labs/kubernetes/lab2

The docs probably need to be updated to reflect the need for `spec.storage` `accessMode` and `volumeMode`, but I figured I'd try to get through to a working VM using CDI before I went that route.

Probably needing to look at some logs for cdi, though initial glances through logs don't see any issues.

```
ii@sharingio:~/infra/vm$ kubectl describe datavolumes.cdi.kubevirt.io fedora 
Name:         fedora
Namespace:    default
Labels:       <none>
Annotations:  cdi.kubevirt.io/storage.usePopulator: true
API Version:  cdi.kubevirt.io/v1beta1
Kind:         DataVolume
Metadata:
  Creation Timestamp:  2024-05-04T20:57:58Z
  Generation:          1
  Resource Version:    748172
  UID:                 aae59fea-ca3e-4f3c-b127-56fec0075888
Spec:
  Source:
    Http:
      URL:  https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz
  Storage:
    Access Modes:
      ReadWriteOnce
    Resources:
      Requests:
        Storage:  5Gi
    Volume Mode:  block
Status:
  Conditions:
    Last Heartbeat Time:   2024-05-04T20:57:58Z
    Last Transition Time:  2024-05-04T20:57:58Z
    Message:               No PVC found
    Reason:                NotFound
    Status:                Unknown
    Type:                  Bound
    Last Heartbeat Time:   2024-05-04T20:57:58Z
    Last Transition Time:  2024-05-04T20:57:58Z
    Status:                False
    Type:                  Ready
    Last Heartbeat Time:   2024-05-04T20:57:58Z
    Last Transition Time:  2024-05-04T20:57:58Z
    Status:                False
    Type:                  Running
  Phase:                   Pending
Events:
  Type    Reason    Age    From                          Message
  ----    ------    ----   ----                          -------
  Normal  NotFound  7m29s  datavolume-import-controller  No PVC found
  ```

**Comment by hh** [comment]
Note the minor updates we needed to get past the first errors. Now we are trying to debug the CDI import. This is a slightly modified version of the here-doc from https://kubevirt.io/labs/kubernetes/lab2:

```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "fedora"
spec:
  storage:
    volumeMode: block # or filesystem -- not in labs walkthrough, but seems required
    accessModes: # -- also not in labs walkthrough, but required
      - ReadWriteOnce # Necessary as it's no longer has a default
    resources:
      requests:
        storage: 5Gi
  source:
    http:
      url: "https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz"
 ```
